/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [7:0] led,
    input on_button,
    input att1_btn1,
    input att1_btn2,
    input att1_btn3,
    input att2_btn1,
    input att2_btn2,
    input att2_btn3,
    input def1_btn1,
    input def1_btn2,
    input def1_btn3,
    input def2_btn1,
    input def2_btn2,
    input def2_btn3
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [16-1:0] M_m_aout;
  wire [16-1:0] M_m_bout;
  wire [2-1:0] M_m_timer;
  wire [4-1:0] M_m_leds;
  reg [16-1:0] M_m_wd;
  reg [4-1:0] M_m_wa;
  reg [4-1:0] M_m_ra;
  reg [4-1:0] M_m_rb;
  reg [16-1:0] M_m_alit;
  reg [16-1:0] M_m_blit;
  reg [1-1:0] M_m_asel;
  reg [1-1:0] M_m_bsel;
  memory_2 m (
    .clk(clk),
    .rst(rst),
    .wd(M_m_wd),
    .wa(M_m_wa),
    .ra(M_m_ra),
    .rb(M_m_rb),
    .alit(M_m_alit),
    .blit(M_m_blit),
    .asel(M_m_asel),
    .bsel(M_m_bsel),
    .aout(M_m_aout),
    .bout(M_m_bout),
    .timer(M_m_timer),
    .leds(M_m_leds)
  );
  localparam IDLE_state = 5'd0;
  localparam OFF_state = 5'd1;
  localparam CAL_TEMP_SCORE1_state = 5'd2;
  localparam CAL_TEMP_SCORE2_state = 5'd3;
  localparam FLIP_TEMP_SCORE1_state = 5'd4;
  localparam FLIP_TEMP_SCORE2_state = 5'd5;
  localparam ADD_SCORE1_state = 5'd6;
  localparam ADD_SCORE2_state = 5'd7;
  localparam CAL_P1L1A_ACTION_state = 5'd8;
  localparam CAL_P1L1D_ACTION_state = 5'd9;
  localparam CAL_P2L1A_ACTION_state = 5'd10;
  localparam CAL_P2L1D_ACTION_state = 5'd11;
  localparam CAL_P1L2A_ACTION_state = 5'd12;
  localparam CAL_P1L2D_ACTION_state = 5'd13;
  localparam CAL_P2L2A_ACTION_state = 5'd14;
  localparam CAL_P2L2D_ACTION_state = 5'd15;
  localparam CAL_P1L3A_ACTION_state = 5'd16;
  localparam CAL_P1L3D_ACTION_state = 5'd17;
  localparam CAL_P2L3A_ACTION_state = 5'd18;
  localparam CAL_P2L3D_ACTION_state = 5'd19;
  localparam CLEAR_ATT1_state = 5'd20;
  localparam CLEAR_ATT2_state = 5'd21;
  localparam CLEAR_DEF1_state = 5'd22;
  localparam CLEAR_DEF2_state = 5'd23;
  
  reg [4:0] M_state_d, M_state_q = IDLE_state;
  reg [25:0] M_sclk_d, M_sclk_q = 1'h0;
  
  wire [16-1:0] M_alu_result;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_fn;
  alu_3 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .fn(M_alu_fn),
    .result(M_alu_result),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_sclk_d = M_sclk_q;
    
    M_sclk_d = M_sclk_q + 1'h1;
    if (M_sclk_q == 26'h2faf081) begin
      M_sclk_d = 1'h0;
    end
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    if (M_sclk_q == 26'h2faf080) begin
      M_m_wa = 1'h1;
      M_m_ra = 1'h1;
      M_m_rb = 1'h0;
      M_m_alit = 1'h0;
      M_m_blit = 1'h1;
      M_m_asel = 1'h0;
      M_m_bsel = 1'h1;
      M_alu_fn = 6'h00;
    end else begin
      
      case (M_state_q)
        IDLE_state: begin
          if (1'h0) begin
            M_m_wa = 2'h2;
            M_m_ra = 2'h2;
            M_m_rb = 1'h0;
            M_m_alit = 1'h0;
            M_m_blit = 1'h1;
            M_m_asel = 1'h0;
            M_m_bsel = 1'h1;
            M_alu_fn = 6'h02;
            M_state_d = OFF_state;
          end else begin
            if (M_m_timer == 2'h0) begin
              M_m_wa = 4'h9;
              M_m_ra = 4'h9;
              M_m_rb = 1'h0;
              M_m_alit = 1'h0;
              M_m_blit = 1'h1;
              M_m_asel = 1'h1;
              M_m_bsel = 1'h1;
              M_alu_fn = 6'h00;
              M_state_d = CLEAR_ATT1_state;
            end else begin
              if (M_m_timer == 2'h1) begin
                M_m_wa = 4'h9;
                M_m_ra = 4'h9;
                M_m_rb = 1'h0;
                M_m_alit = 1'h0;
                M_m_blit = 2'h3;
                M_m_asel = 1'h1;
                M_m_bsel = 1'h1;
                M_alu_fn = 6'h00;
                M_state_d = IDLE_state;
              end else begin
                if (M_m_timer == 2'h2) begin
                  M_m_wa = 4'h9;
                  M_m_ra = 4'h9;
                  M_m_rb = 1'h0;
                  M_m_alit = 1'h0;
                  M_m_blit = 3'h7;
                  M_m_asel = 1'h1;
                  M_m_bsel = 1'h1;
                  M_alu_fn = 6'h00;
                  M_state_d = IDLE_state;
                end else begin
                  if (M_m_timer == 2'h3) begin
                    M_m_wa = 4'h9;
                    M_m_ra = 4'h9;
                    M_m_rb = 1'h0;
                    M_m_alit = 1'h0;
                    M_m_blit = 4'hf;
                    M_m_asel = 1'h1;
                    M_m_bsel = 1'h1;
                    M_alu_fn = 6'h00;
                    M_state_d = CAL_TEMP_SCORE1_state;
                  end else begin
                    if (att1_btn1) begin
                      M_m_wa = 2'h3;
                      M_m_ra = 1'h0;
                      M_m_rb = 1'h0;
                      M_m_alit = 3'h4;
                      M_m_blit = 1'h0;
                      M_m_asel = 1'h1;
                      M_m_bsel = 1'h1;
                      M_alu_fn = 6'h00;
                      M_state_d = IDLE_state;
                    end else begin
                      if (att1_btn2) begin
                        M_m_wa = 2'h3;
                        M_m_ra = 1'h0;
                        M_m_rb = 1'h0;
                        M_m_alit = 3'h2;
                        M_m_blit = 1'h0;
                        M_m_asel = 1'h1;
                        M_m_bsel = 1'h1;
                        M_alu_fn = 6'h00;
                        M_state_d = IDLE_state;
                      end else begin
                        if (att1_btn3) begin
                          M_m_wa = 2'h3;
                          M_m_ra = 1'h0;
                          M_m_rb = 1'h0;
                          M_m_alit = 3'h1;
                          M_m_blit = 1'h0;
                          M_m_asel = 1'h1;
                          M_m_bsel = 1'h1;
                          M_alu_fn = 6'h00;
                          M_state_d = IDLE_state;
                        end else begin
                          if (def1_btn1) begin
                            M_m_wa = 3'h4;
                            M_m_ra = 1'h0;
                            M_m_rb = 1'h0;
                            M_m_alit = 3'h4;
                            M_m_blit = 1'h0;
                            M_m_asel = 1'h1;
                            M_m_bsel = 1'h1;
                            M_alu_fn = 6'h00;
                            M_state_d = IDLE_state;
                          end else begin
                            if (def1_btn2) begin
                              M_m_wa = 3'h4;
                              M_m_ra = 1'h0;
                              M_m_rb = 1'h0;
                              M_m_alit = 3'h2;
                              M_m_blit = 1'h0;
                              M_m_asel = 1'h1;
                              M_m_bsel = 1'h1;
                              M_alu_fn = 6'h00;
                              M_state_d = IDLE_state;
                            end else begin
                              if (def1_btn3) begin
                                M_m_wa = 3'h4;
                                M_m_ra = 1'h0;
                                M_m_rb = 1'h0;
                                M_m_alit = 3'h1;
                                M_m_blit = 1'h0;
                                M_m_asel = 1'h1;
                                M_m_bsel = 1'h1;
                                M_alu_fn = 6'h00;
                                M_state_d = IDLE_state;
                              end else begin
                                if (att2_btn1) begin
                                  M_m_wa = 3'h6;
                                  M_m_ra = 1'h0;
                                  M_m_rb = 1'h0;
                                  M_m_alit = 3'h4;
                                  M_m_blit = 1'h0;
                                  M_m_asel = 1'h1;
                                  M_m_bsel = 1'h1;
                                  M_alu_fn = 6'h00;
                                  M_state_d = IDLE_state;
                                end else begin
                                  if (att2_btn2) begin
                                    M_m_wa = 3'h6;
                                    M_m_ra = 1'h0;
                                    M_m_rb = 1'h0;
                                    M_m_alit = 3'h2;
                                    M_m_blit = 1'h0;
                                    M_m_asel = 1'h1;
                                    M_m_bsel = 1'h1;
                                    M_alu_fn = 6'h00;
                                    M_state_d = IDLE_state;
                                  end else begin
                                    if (att2_btn3) begin
                                      M_m_wa = 3'h6;
                                      M_m_ra = 1'h0;
                                      M_m_rb = 1'h0;
                                      M_m_alit = 3'h1;
                                      M_m_blit = 1'h0;
                                      M_m_asel = 1'h1;
                                      M_m_bsel = 1'h1;
                                      M_alu_fn = 6'h00;
                                      M_state_d = IDLE_state;
                                    end else begin
                                      if (def2_btn1) begin
                                        M_m_wa = 3'h7;
                                        M_m_ra = 1'h0;
                                        M_m_rb = 1'h0;
                                        M_m_alit = 3'h4;
                                        M_m_blit = 1'h0;
                                        M_m_asel = 1'h1;
                                        M_m_bsel = 1'h1;
                                        M_alu_fn = 6'h00;
                                        M_state_d = IDLE_state;
                                      end else begin
                                        if (def2_btn2) begin
                                          M_m_wa = 3'h7;
                                          M_m_ra = 1'h0;
                                          M_m_rb = 1'h0;
                                          M_m_alit = 3'h2;
                                          M_m_blit = 1'h0;
                                          M_m_asel = 1'h1;
                                          M_m_bsel = 1'h1;
                                          M_alu_fn = 6'h00;
                                          M_state_d = IDLE_state;
                                        end else begin
                                          if (def2_btn3) begin
                                            M_m_wa = 3'h7;
                                            M_m_ra = 1'h0;
                                            M_m_rb = 1'h0;
                                            M_m_alit = 3'h1;
                                            M_m_blit = 1'h0;
                                            M_m_asel = 1'h1;
                                            M_m_bsel = 1'h1;
                                            M_alu_fn = 6'h00;
                                            M_state_d = IDLE_state;
                                          end else begin
                                            M_m_wa = 4'hf;
                                            M_m_ra = 4'hf;
                                            M_m_rb = 4'hf;
                                            M_m_alit = 1'h0;
                                            M_m_blit = 1'h0;
                                            M_m_asel = 1'h0;
                                            M_m_bsel = 1'h0;
                                            M_alu_fn = 6'h00;
                                            M_state_d = IDLE_state;
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
        CAL_TEMP_SCORE1_state: begin
          M_m_wa = 4'ha;
          M_m_ra = 2'h3;
          M_m_rb = 3'h7;
          M_m_alit = 1'h0;
          M_m_blit = 1'h0;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h0;
          M_alu_fn = 6'h32;
          M_state_d = CAL_TEMP_SCORE2_state;
        end
        CAL_TEMP_SCORE2_state: begin
          M_m_wa = 4'hb;
          M_m_ra = 3'h6;
          M_m_rb = 3'h4;
          M_m_alit = 1'h0;
          M_m_blit = 1'h0;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h0;
          M_alu_fn = 6'h32;
          M_state_d = FLIP_TEMP_SCORE1_state;
        end
        FLIP_TEMP_SCORE1_state: begin
          M_m_wa = 4'ha;
          M_m_ra = 4'ha;
          M_m_rb = 1'h0;
          M_m_alit = 1'h0;
          M_m_blit = 1'h1;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h1;
          M_alu_fn = 6'h16;
          M_state_d = FLIP_TEMP_SCORE2_state;
        end
        FLIP_TEMP_SCORE2_state: begin
          M_m_wa = 4'hb;
          M_m_ra = 4'hb;
          M_m_rb = 1'h0;
          M_m_alit = 1'h0;
          M_m_blit = 1'h1;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h1;
          M_alu_fn = 6'h16;
          M_state_d = ADD_SCORE1_state;
        end
        ADD_SCORE1_state: begin
          M_m_wa = 3'h5;
          M_m_ra = 3'h5;
          M_m_rb = 4'ha;
          M_m_alit = 1'h0;
          M_m_blit = 1'h0;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h0;
          M_alu_fn = 6'h00;
          M_state_d = ADD_SCORE2_state;
        end
        ADD_SCORE2_state: begin
          M_m_wa = 4'h8;
          M_m_ra = 4'h8;
          M_m_rb = 4'hb;
          M_m_alit = 1'h0;
          M_m_blit = 1'h0;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h0;
          M_alu_fn = 6'h00;
          M_state_d = CAL_P1L1A_ACTION_state;
        end
        CAL_P1L1A_ACTION_state: begin
          M_state_d = CAL_P1L1D_ACTION_state;
        end
        CAL_P1L1D_ACTION_state: begin
          M_state_d = CAL_P2L1A_ACTION_state;
        end
        CAL_P2L1A_ACTION_state: begin
          M_state_d = CAL_P2L1D_ACTION_state;
        end
        CAL_P2L1D_ACTION_state: begin
          M_state_d = CAL_P1L2A_ACTION_state;
        end
        CAL_P1L2A_ACTION_state: begin
          M_state_d = CAL_P1L2D_ACTION_state;
        end
        CAL_P1L2D_ACTION_state: begin
          M_state_d = CAL_P2L2A_ACTION_state;
        end
        CAL_P2L2A_ACTION_state: begin
          M_state_d = CAL_P2L2D_ACTION_state;
        end
        CAL_P2L2D_ACTION_state: begin
          M_state_d = CAL_P1L3A_ACTION_state;
        end
        CAL_P1L3A_ACTION_state: begin
          M_state_d = CAL_P1L3D_ACTION_state;
        end
        CAL_P1L3D_ACTION_state: begin
          M_state_d = CAL_P2L3A_ACTION_state;
        end
        CAL_P2L3A_ACTION_state: begin
          M_state_d = CAL_P2L3D_ACTION_state;
        end
        CAL_P2L3D_ACTION_state: begin
          M_state_d = IDLE_state;
        end
        CLEAR_ATT1_state: begin
          M_m_wa = 2'h3;
          M_m_ra = 2'h3;
          M_m_rb = 1'h0;
          M_m_alit = 1'h0;
          M_m_blit = 2'h3;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h1;
          M_alu_fn = 6'h21;
          M_state_d = CLEAR_ATT2_state;
        end
        CLEAR_ATT2_state: begin
          M_m_wa = 3'h6;
          M_m_ra = 3'h6;
          M_m_rb = 1'h0;
          M_m_alit = 1'h0;
          M_m_blit = 2'h3;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h1;
          M_alu_fn = 6'h21;
          M_state_d = CLEAR_DEF1_state;
        end
        CLEAR_DEF1_state: begin
          M_m_wa = 3'h4;
          M_m_ra = 3'h4;
          M_m_rb = 1'h0;
          M_m_alit = 1'h0;
          M_m_blit = 2'h3;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h1;
          M_alu_fn = 6'h21;
          M_state_d = CLEAR_DEF2_state;
        end
        CLEAR_DEF2_state: begin
          M_m_wa = 3'h7;
          M_m_ra = 3'h7;
          M_m_rb = 1'h0;
          M_m_alit = 1'h0;
          M_m_blit = 2'h3;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h1;
          M_alu_fn = 6'h21;
          M_state_d = IDLE_state;
        end
        default: begin
          M_m_wa = 4'hf;
          M_m_ra = 4'hf;
          M_m_rb = 1'h0;
          M_m_alit = 1'h0;
          M_m_blit = 1'h0;
          M_m_asel = 1'h0;
          M_m_bsel = 1'h0;
          M_alu_fn = 6'h00;
          M_state_d = IDLE_state;
        end
      endcase
    end
    M_alu_a = M_m_aout;
    M_alu_b = M_m_bout;
    led = {M_m_leds, 2'h0, M_m_timer};
    M_m_wd = M_alu_result;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_sclk_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_sclk_q <= M_sclk_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
