/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module memory_2 (
    input clk,
    input rst,
    input [15:0] wd,
    input [3:0] wa,
    input [3:0] ra,
    input [3:0] rb,
    input [15:0] alit,
    input [15:0] blit,
    input [0:0] asel,
    input [0:0] bsel,
    output reg [15:0] aout,
    output reg [15:0] bout,
    output reg [1:0] timer,
    output reg [3:0] leds
  );
  
  
  
  reg [239:0] M_reg_d, M_reg_q = 1'h0;
  
  always @* begin
    M_reg_d = M_reg_q;
    
    M_reg_d[(wa)*16+15-:16] = wd;
    if (asel) begin
      aout = alit;
    end else begin
      aout = M_reg_q[(ra)*16+15-:16];
    end
    if (bsel) begin
      bout = blit;
    end else begin
      bout = M_reg_q[(rb)*16+15-:16];
    end
    timer = M_reg_q[16+0+1-:2];
    leds = M_reg_q[144+0+3-:4];
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_reg_q <= 1'h0;
    end else begin
      M_reg_q <= M_reg_d;
    end
  end
  
endmodule
